version: "3"

services:
    backend:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes: 
            - ./backend:/backend
        command: >
          sh -c "python manage.py wait_for_db && 
                 python manage.py migrate &&
                 python manage.py runserver 0.0.0.0:8000"
        environment:
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASS=717rco66
        depends_on: 
            - db
    db:
        image: postgres:alpine
        container_name: food_db
        environment: 
            - POSTGRES_DB=food
            - POSTGRES_USER=haupai
            - POSTGRES_PASSWORD=717rco66
        ports:
            - '5432:5432'

    adminer:
        image: adminer
        container_name: food-db-adminer
        restart: always
        ports:
            - '8080:8080'
